name: Go

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Download Pact
      working-directory: ~/
      run: curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.80/pact-1.88.80-linux-x86_64.tar.gz
      
    - name: Extract Pact
      working-directory: ~/
      run: tar xzf pact-1.88.80-linux-x86_64.tar.gz
      
    - name: Add Pact to PATH
      run: echo "{path}" >> ~/pact/bin
      
    - name: Check Path
      run: echo "{path}"
      
    - name: Test
      run: go test -v ./...
